sudo: required
services:
  - docker

before_install:
  - docker build -t mzinsser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mzinsser/react-test npm test

after_success: 
  - docker build -t mzinsser/multi-client ./client
  - docker build -t mzinsser/multi-nginx ./nginx
  - docker build -t mzinsser/multi-server ./server
  - docker build -t mzinsser/multi-worker ./worker

  # log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mzinsser/multi-client
  - docker push mzinsser/multi-nginx
  - docker push mzinsser/multi-server
  - docker push mzinsser/multi-worker